# Generated by Django 2.1.3 on 2018-11-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_readingtip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingtip',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='readingtip',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='readingtip',
            name='url',
            field=models.CharField(max_length=20, verbose_name='URL'),
        ),
    ]
