# Generated by Django 2.1.3 on 2018-11-20 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181119_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTipContentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTipContentWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='readingtip',
            name='url',
        ),
        migrations.AddField(
            model_name='readingtip',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'A'), (1, 'B')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reading_tips', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtipcontentwebsite',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='app.ReadingTip'),
        ),
        migrations.AddField(
            model_name='readingtipcontentbook',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.ReadingTip'),
        ),
    ]
