# Generated by Django 2.1.3 on 2018-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181120_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingtip',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'Book'), (1, 'Website')]),
        ),
    ]
