# Generated by Django 2.1.3 on 2018-11-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181120_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingtipcontentbook',
            options={'get_latest_by': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='readingtipcontentwebsite',
            options={'get_latest_by': ('-id',)},
        ),
    ]
