# Generated by Django 2.1.3 on 2018-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181120_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtip',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
    ]
