# Generated by Django 2.1.3 on 2018-11-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_readingtip_has_been_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtip',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
