# Generated by Django 2.1.3 on 2018-11-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_readingtip_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingtipcontentbook',
            options={'get_latest_by': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='readingtipcontentwebsite',
            options={'get_latest_by': ('id',)},
        ),
    ]
