# Generated by Django 2.1.3 on 2018-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181127_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingtip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
